//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidades
    {
        public int UF { get; set; }
        public string Nome_UF { get; set; }
        public int Mesorregiao_Geografica { get; set; }
        public string Nome_Mesorregiao { get; set; }
        public int Microrregiao_Geografica { get; set; }
        public string Nome_Microrregiao { get; set; }
        public int Municipio { get; set; }
        public int Cod_Municipio_Completo { get; set; }
        public string Nome_Municipio { get; set; }
    }
}
