//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienteVeiculo
    {
        public int cod { get; set; }
        public Nullable<int> codCliente { get; set; }
        public Nullable<int> codVeiculo { get; set; }
        public string placa { get; set; }
    
        public virtual modelo modelo { get; set; }
    }
}
