//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int cod { get; set; }
        public string assunto { get; set; }
        public string corpo { get; set; }
        public string rodape1 { get; set; }
        public string rodape2 { get; set; }
        public string rodape3 { get; set; }
    }
}
