//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class itensvenda
    {
        public int itv_cod { get; set; }
        public Nullable<double> itv_qtde { get; set; }
        public Nullable<decimal> itv_valor { get; set; }
        public Nullable<int> ven_cod { get; set; }
        public Nullable<int> cp_cod { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> itv_valorBase { get; set; }
        public Nullable<decimal> itv_desconto { get; set; }
        public Nullable<int> op_cod { get; set; }
    
        public virtual operacao operacao { get; set; }
        public virtual venda venda { get; set; }
        public virtual ClienteProduto ClienteProduto { get; set; }
    }
}
