//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class lembrete
    {
        public int cod { get; set; }
        public Nullable<int> diasAviso { get; set; }
        public string mensagemAviso { get; set; }
        public string tituloAviso { get; set; }
    }
}
