//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modelo()
        {
            this.clienteVeiculo = new HashSet<clienteVeiculo>();
        }
    
        public int cod { get; set; }
        public Nullable<int> codMontadora { get; set; }
        public string modelo1 { get; set; }
        public Nullable<int> anoInicio { get; set; }
        public Nullable<int> anoFim { get; set; }
        public Nullable<System.DateTime> cadastro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clienteVeiculo> clienteVeiculo { get; set; }
        public virtual montadora montadora { get; set; }
    }
}
