//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.ClienteProduto = new HashSet<ClienteProduto>();
        }
    
        public int pro_cod { get; set; }
        public string pro_nome { get; set; }
        public string pro_descricao { get; set; }
        public string pro_foto { get; set; }
        public Nullable<decimal> pro_valorpago { get; set; }
        public Nullable<decimal> pro_valorvenda { get; set; }
        public Nullable<double> pro_qtde { get; set; }
        public string umed { get; set; }
        public Nullable<int> cat_cod { get; set; }
        public Nullable<int> scat_cod { get; set; }
        public Nullable<System.DateTime> pro_cadastro { get; set; }
        public Nullable<int> for_cod { get; set; }
        public string pro_ref { get; set; }
        public string localizacao { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteProduto> ClienteProduto { get; set; }
        public virtual fornecedor fornecedor { get; set; }
        public virtual subcategoria subcategoria { get; set; }
    }
}
