//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class promissumServicoEntities : DbContext
    {
        public promissumServicoEntities()
            : base("name=promissumServicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clienteVeiculo> clienteVeiculo { get; set; }
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<itensvenda> itensvenda { get; set; }
        public virtual DbSet<lembrete> lembrete { get; set; }
        public virtual DbSet<modelo> modelo { get; set; }
        public virtual DbSet<montadora> montadora { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venda> venda { get; set; }
        public virtual DbSet<cidades> cidades { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<ClienteProduto> ClienteProduto { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<operacao> operacao { get; set; }
        public virtual DbSet<subcategoria> subcategoria { get; set; }
    }
}
